# models.py - SQLAlchemy ORM models for all database tables

import json
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Text
from sqlalchemy.orm import relationship
from database import Base


class Room(Base):
    """
    Represents a quiz room.
    - room_code: unique 6-character code shared with participants
    - status: 'waiting' | 'started' | 'closed'
    """
    __tablename__ = "rooms"

    id = Column(Integer, primary_key=True, index=True)
    room_code = Column(String(6), unique=True, index=True, nullable=False)
    admin_name = Column(String(100), nullable=False)
    quiz_topic = Column(String(200), nullable=False)
    difficulty = Column(String(10), nullable=False)   # easy / medium / hard
    num_questions = Column(Integer, nullable=False)
    question_type = Column(String(10), nullable=False) # mcq / blank
    status = Column(String(10), default="waiting")     # waiting / started / closed
    created_at = Column(String(50), nullable=True)

    # Relationships
    users = relationship("User", back_populates="room", cascade="all, delete-orphan")
    questions = relationship("Question", back_populates="room", cascade="all, delete-orphan")


class Account(Base):
    """
    Represents a login account for a browser identity.
    - email: unique sign-in identifier
    - password_hash: salted password hash stored server-side
    """
    __tablename__ = "accounts"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    password_hash = Column(Text, nullable=False)
    created_at = Column(String(50), nullable=True)


class User(Base):
    """
    Represents a participant (or admin) in a room.
    - is_admin: True for the room creator
    - score: accumulated score after quiz
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    email = Column(String(255), nullable=False, index=True)
    room_id = Column(Integer, ForeignKey("rooms.id"), nullable=False)
    score = Column(Integer, default=0)
    is_admin = Column(Boolean, default=False)

    # Relationships
    room = relationship("Room", back_populates="users")
    answers = relationship("Answer", back_populates="user", cascade="all, delete-orphan")


class Question(Base):
    """
    Represents a quiz question generated by AI.
    - options_json: JSON string storing MCQ options list
    - correct_answer: expected answer string
    """
    __tablename__ = "questions"

    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(Integer, ForeignKey("rooms.id"), nullable=False)
    question_text = Column(Text, nullable=False)
    type = Column(String(10), nullable=False)   # mcq / blank
    options_json = Column(Text, nullable=True)  # JSON array for MCQ options
    correct_answer = Column(Text, nullable=False)

    # Relationships
    room = relationship("Room", back_populates="questions")
    answers = relationship("Answer", back_populates="question", cascade="all, delete-orphan")

    @property
    def options(self):
        """Parse options from JSON string to Python list."""
        if self.options_json:
            return json.loads(self.options_json)
        return []

    @options.setter
    def options(self, value):
        """Store options list as JSON string."""
        self.options_json = json.dumps(value) if value else None


class Answer(Base):
    """
    Stores a user's answer to a specific question.
    - is_correct: auto-set for MCQ; manually/AI-set for blanks
    """
    __tablename__ = "answers"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    question_id = Column(Integer, ForeignKey("questions.id"), nullable=False)
    answer = Column(Text, nullable=False)
    is_correct = Column(Boolean, default=False)

    # Relationships
    user = relationship("User", back_populates="answers")
    question = relationship("Question", back_populates="answers")
